// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVCDocker.Models;

public partial class ItemMaster
{
    public int Id { get; set; }

    public string ItemName { get; set; }

    public bool? IsRateApplicable { get; set; }

    public decimal? Rate { get; set; }

    public bool? IsGstaplicable { get; set; }

    public decimal? Gstrate { get; set; }

    public string Hsnno { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public bool? Active { get; set; }
}