// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MVCDocker.Models;

public partial class UserMaster
{
    public int Id { get; set; }

    public string PersonName { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public int? RoleId { get; set; }

    public DateTime? CreatedOn { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? ModifiedOn { get; set; }

    public int? ModifiedBy { get; set; }

    public bool? Active { get; set; }
}